name: jpackage
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 构建项目
        run: |
          ./gradlew clean jpackage

      - name: 获取版本号
        id: get_version
        shell: pwsh
        run: |
          $folder = Get-ChildItem ./build/jpackage | Where-Object { $_.Name -match '^AutoETSHomework-\d+\.\d+\.\d+$' } | Select-Object -First 1
          if ($folder) {
            $version = $folder.Name -replace '^AutoETSHomework-',''
            echo "version=$version" >> $env:GITHUB_OUTPUT
          }

      - name: 打包产物为 zip
        shell: pwsh
        run: |
          $src = "./build/jpackage/AutoETSHomework-${{ steps.get_version.outputs.version }}"
          mkdir dist
          Copy-Item "$src\*.exe" dist
          Copy-Item "$src\app" dist -Recurse
          Copy-Item "$src\runtime" dist -Recurse
          Compress-Archive -Path dist\* -DestinationPath "dist/AutoETSHomework-${{ steps.get_version.outputs.version }}.zip"

      - name: 创建 Release 并上传产物
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: AutoETSHomework-${{ steps.get_version.outputs.version }}
          draft: true
          files: dist/*